[SP-2762] Backport of PDI-15260 - Model built using Spoon Agile is not getting published to the BA server. (6.1 Suite)
When publishing model from agile-bi we are [creating an instance of DatabaseDialectService](https://github.com/pentaho/pdi-agile-bi-plugin/blob/master/src/org/pentaho/agilebi/spoon/publish/ModelServerPublish.java#L341) class.

But we run into [ServiceConfigurationError](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceConfigurationError.html) wrapped into NoClassDeffoundError because static fields cannot be initialized properly.

It happens because `ServiceLoader#load(Class<S> service)` loads classes with the help of `Thread.currentThread().getContextClassLoader()` classloader.
Thats not what we want here, as DatabaseDialectService and other pentaho-database-model classes are loaded via [Kettels own classloader] (https://github.com/pentaho/pentaho-kettle/blob/master/core/src/org/pentaho/di/core/plugins/KettleURLClassLoader.java), that is a child of thread's content classloader.
So we enforce ServiceLoader to load classes from the same classloader, that DatabaseDialectService class was loaded from.

I also removed Logger, as it is not used anywhere.